name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Triggers when repository is starred.
  watch: 

jobs:
  build:
    strategy:
      matrix:
        run: [1,2,3,4,5,6,7,8,9,10]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/fakutori/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Install dependencies
      env:
        NUGET_AUTH_TOKEN: ${{secrets.READ_PACKAGES_TOKEN}}
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run the application
      run: dotnet run --no-build
